//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// BetBook
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const betBookAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'initialMembers', internalType: 'address[]', type: 'address[]' },
      { name: 'names', internalType: 'string[]', type: 'string[]' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'NO_BET',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'VOTE_WINDOW',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'acceptBet',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'who', internalType: 'address', type: 'address' },
      { name: 'name', internalType: 'string', type: 'string' },
    ],
    name: 'addMember',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'betCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'cancelBet',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'o', internalType: 'enum BetBook.Outcome', type: 'uint8' },
    ],
    name: 'claimOutcome',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'declineBet',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'eligibleVoterCount',
    outputs: [{ name: 'eligible', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'escalate',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'finalizeVote',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'getBet',
    outputs: [
      {
        name: '',
        internalType: 'struct BetBook.Bet',
        type: 'tuple',
        components: [
          { name: 'maker', internalType: 'address', type: 'address' },
          { name: 'taker', internalType: 'address', type: 'address' },
          { name: 'description', internalType: 'string', type: 'string' },
          { name: 'stakeQty', internalType: 'uint32', type: 'uint32' },
          { name: 'stakeUnit', internalType: 'string', type: 'string' },
          { name: 'acceptBy', internalType: 'uint64', type: 'uint64' },
          { name: 'claimedAt', internalType: 'uint64', type: 'uint64' },
          { name: 'disputedAt', internalType: 'uint64', type: 'uint64' },
          {
            name: 'status',
            internalType: 'enum BetBook.Status',
            type: 'uint8',
          },
          {
            name: 'claimedOutcome',
            internalType: 'enum BetBook.Outcome',
            type: 'uint8',
          },
          { name: 'claimant', internalType: 'address', type: 'address' },
          {
            name: 'outcome',
            internalType: 'enum BetBook.Outcome',
            type: 'uint8',
          },
          { name: 'votesMaker', internalType: 'uint32', type: 'uint32' },
          { name: 'votesTaker', internalType: 'uint32', type: 'uint32' },
          { name: 'votesPush', internalType: 'uint32', type: 'uint32' },
          { name: 'parentId', internalType: 'uint256', type: 'uint256' },
          { name: 'childId', internalType: 'uint256', type: 'uint256' },
          { name: 'isDouble', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'address', type: 'address' },
    ],
    name: 'hasVoted',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'markSettled',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'memberCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'memberList',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'members',
    outputs: [
      { name: 'name', internalType: 'string', type: 'string' },
      { name: 'joinedAt', internalType: 'uint64', type: 'uint64' },
      { name: 'exists', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'taker', internalType: 'address', type: 'address' },
      { name: 'description', internalType: 'string', type: 'string' },
      { name: 'stakeQty', internalType: 'uint32', type: 'uint32' },
      { name: 'stakeUnit', internalType: 'string', type: 'string' },
      { name: 'acceptBy', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'proposeBet',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'parentId', internalType: 'uint256', type: 'uint256' },
      { name: 'description', internalType: 'string', type: 'string' },
      { name: 'acceptBy', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'proposeDoubleOrNothing',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'o', internalType: 'enum BetBook.Outcome', type: 'uint8' },
    ],
    name: 'respondToClaim',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'name', internalType: 'string', type: 'string' }],
    name: 'setMyName',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'o', internalType: 'enum BetBook.Outcome', type: 'uint8' },
    ],
    name: 'vote',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'BetAccepted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'BetCanceled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'BetDeclined',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'maker',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'taker',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'description',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
      {
        name: 'stakeQty',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
      {
        name: 'stakeUnit',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
      {
        name: 'acceptBy',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: 'parentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BetProposed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'outcome',
        internalType: 'enum BetBook.Outcome',
        type: 'uint8',
        indexed: false,
      },
      { name: 'byVote', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'BetResolved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'markedBy',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'BetSettled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'parentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'childId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'BetSuperseded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'disputer',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'counterClaim',
        internalType: 'enum BetBook.Outcome',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'ClaimDisputed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'addedBy',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'name', internalType: 'string', type: 'string', indexed: false },
    ],
    name: 'MemberAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'name', internalType: 'string', type: 'string', indexed: false },
    ],
    name: 'NameChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'claimant',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'outcome',
        internalType: 'enum BetBook.Outcome',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'OutcomeClaimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'parentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'childId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'ParentRestored',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      {
        name: 'voter',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'outcome',
        internalType: 'enum BetBook.Outcome',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'VoteCast',
  },
] as const
